import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NavBar from '@components/common/NavBar';
import { CSPostHogProvider } from '@lib/providers';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <CSPostHogProvider>
        <body className={inter.className + ' mx-auto max-w-lg px-3 sm:px-0'}>
          <NavBar />
          {children}
        </body>
      </CSPostHogProvider>
    </html>
  );
}
